application: datastore-key
version: 0-0-1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static/default
  expiration: "1h"
- url: /cachable_.*_
  static_dir: static/default
  expiration: "364d"
- url: /admin.*
  script: _go_app
  login: admin
- url: /.*
  script: _go_app